### ISSUE TITLE
Attach dbaccess.py with GUI calls to database

### ISSUE THREAD

**Issue by mjmiller20** [mjmiller20/OOPM#40]
Implement button functionality with forms in GUI to call functions in DBAccess

**Comment by ecargin1** [comment]
Added db calls for New Reservations and View Option.  Errors in View Option page on branch: https://github.com/mjmiller20/OOPM/tree/ecargin/reservation_db_calls
@mjmiller20 @JoelASeepersaud @ddevrie300
